site_name: Open Management
site_url: https://aristanetworks.github.io/openmgmt/
theme: mkdocs
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: orange
extra:
  analytics:
    provider: google
    property: G-4V8W728SS9
