name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '39 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 180
        days-before-issue-close: 14
        stale-issue-message: 'Stale issue message'
        stale-issue-label: 'no-issue-activity'
        days-before-pr-close: 14
        stale-pr-message: 'Stale pull request message'
        stale-pr-label: 'no-pr-activity'
